function Hd = butter_bp_test1
%BUTTER_BP_TEST1 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.6 and Signal Processing Toolbox 8.2.
% Generated on: 14-Jul-2019 12:11:46

% Butterworth Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
Fs = 5000;  % Sampling Frequency

N   = 10;    % Order
Fc1 = 500;   % First Cutoff Frequency
Fc2 = 2000;  % Second Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.bandpass('N,F3dB1,F3dB2', N, Fc1, Fc2, Fs);
Hd = design(h, 'butter');

% [EOF]
