function Hd = butter_filter_spec_ordr(n, fc1, fc2)
%   Passes signal through Butterworth IIR bandpass filter with adjustable order and
%   cutoff frequencies
%   INPUTS
%   n - order
%   fc1 - cutoff frequency 1
%   fc2 - cutoff frequency 2
%BUTTER_FILTER_SPEC_ORDR Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.6 and Signal Processing Toolbox 8.2.
% Generated on: 28-Jul-2019 13:39:56

% Butterworth Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
Fs = 16000;  % Sampling Frequency

N   = n;   % Order
Fc1 = fc1;  % First Cutoff Frequency
Fc2 = fc2;  % Second Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.bandpass('N,F3dB1,F3dB2', N, Fc1, Fc2, Fs);
Hd = design(h, 'butter');

% [EOF]
